from __future__ import annotations

import json
from datetime import datetime
from typing import Any

from .analyzer import analyze, summarize
from .ir import PlcProject


def _status_icon(status: str) -> str:
    icons = {"INFO": "ℹ️", "WARNING": "⚠️", "ERROR": "❌", "SUCCESS": "✅"}
    return icons.get(status, "•")


def build_report(project: PlcProject) -> dict:
    return {
        "metadata": {
            "report_generated": datetime.utcnow().isoformat(),
            "tool_version": "1.2.0",
            "project_file": project.path,
        },
        "summary": summarize(project),
        "analysis": [
            {
                "status": finding.status,
                "title": finding.title,
                "detail": finding.detail,
            }
            for finding in analyze(project)
        ],
        "project_metadata": project.metadata,
        "evidence": [
            {
                "source": evidence.source,
                "item": evidence.item,
                "detail": evidence.detail,
                "confidence": evidence.confidence,
            }
            for evidence in project.evidence
        ],
        "warnings": project.warnings,
    }


def report_json(project: PlcProject) -> str:
    return json.dumps(build_report(project), indent=2)


def report_markdown(project: PlcProject) -> str:
    lines = []
    lines.append(f"# PLC-XRAY Inspection Report\n")
    lines.append(f"**Project:** {project.project_name}  ")
    lines.append(f"**Format:** {project.format}  ")
    lines.append(f"**Timestamp:** {datetime.utcnow().isoformat()}\n")

    lines.append("## Summary\n")
    summary = summarize(project)
    lines.append(f"- **File:** `{project.path}`")
    lines.append(f"- **SHA-256:** `{project.sha256}`")
    lines.append(f"- **File Size:** {summary['file_size']:,} bytes")
    lines.append(f"- **Streams:** {summary['stream_count']}")
    lines.append(f"- **POUs:** {summary['pou_count']}")
    lines.append(f"- **Labels:** {summary['label_count']}")
    lines.append(f"- **Devices:** {summary['device_count']}\n")

    lines.append("## Findings\n")
    for finding in analyze(project):
        icon = _status_icon(finding.status)
        lines.append(f"### {icon} {finding.title}")
        lines.append(f"{finding.detail}\n")

    if project.metadata:
        lines.append("## Metadata\n")
        for key, value in project.metadata.items():
            lines.append(f"- **{key}:** `{value}`")
        lines.append("")

    if project.evidence:
        lines.append("## Evidence\n")
        for evidence in project.evidence:
            conf_badge = f"[{evidence.confidence.upper()}]"
            lines.append(f"- {evidence.source} / {evidence.item} {conf_badge}: {evidence.detail}")
        lines.append("")

    if project.warnings:
        lines.append("## Warnings\n")
        for warning in project.warnings:
            lines.append(f"- ⚠️ {warning}")
        lines.append("")

    lines.append("---\n")
    lines.append("*This report is generated by PLC-XRAY v1.2.0 (read-only container inspection)*\n")
    lines.append("*Native GX Works verification is not performed by this tool.*\n")

    return "\n".join(lines)


__all__ = ["build_report", "report_json", "report_markdown"]
